# following this for front end build - https://betterprogramming.pub/4-steps-to-dockerize-your-next-js-app-cfa8a54881af
version: "3.9" # optional since v1.27.0
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file: .env
    depends_on:
      - db
  db:
    image: "postgres:14"
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./seed_scripts:/docker-entrypoint-initdb.d
    env_file: .env
volumes:
  db_data: {}
