import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { ITransaction } from "../src/types";

// components
import TransactionForm from "../src/components/TransactionForm";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Expense Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={`${styles.title} test-me`}>
          Welcome to Expense Tracker!
        </h1>
        <TransactionForm />
      </main>
    </div>
  );
}
