import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Toggler } from "../src/components/FetchDataOnLoad";
import { ITransaction } from "../src/types";
// import { TestForm } from "../src/components/FormInput";

// components
import FetchDataOnLoad from "../src/components/FetchDataOnLoad";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Expense Tracker!</h1>

        {/* <FetchDataOnLoad id={5} testDate={new Date("2020-2-29")} /> */}
        <Toggler />
        <Toggler />
        <Toggler />
        {/* <TestForm /> */}
      </main>
    </div>
  );
}
