# matrix strategy usage to run one job for multiple project repos found here:
# https://stackoverflow.com/questions/65855054/can-you-have-multiple-working-directories-with-github-actions
name: Github Actions Test
on:
  push:
    branches: [main]
jobs:
  Test-Action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - "frontend"
          - "backend"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
        working-directory: ./${{ matrix.dir }}
      - run: npm run test
        working-directory: ./${{ matrix.dir }}
